service: ${env:PRJ}-service
custom:
  secrets:
    dev: 
      #db_creds: ${ssm:/aws/reference/secretsmanager/${env:ENV}/db-creds-true}
      db_user: test
      #db_host: ${ssm:/${env:ENV}/db-host}
      db_password: test_password
      db_port: 3306
      #account_id: ${ssm:/${env:ENV}/account-id}
      #region: ${ssm:/${env:ENV}/region}
    #local: ${file(local_secrets.json)}
provider:
  name: aws
  runtime: python3.7
  deploymentBucket:
    name: bucket
  role: lambda_role
  stage:  ${opt:stage,'dev'}
  region: eu-central-1
  vpc:
    securityGroupIds:
      - ${ssm:/${env:ENV}/lambda-sg}
    subnetIds:
      - subnet-00e084b77ea3e2a39
      - subnet-0211544261d81e46f
  environment:
    #DB_NAME: ${self:custom.secrets.${self:provider.stage}.db_name}
    DB_USER: ${self:custom.secrets.${self:provider.stage}.db_user}
    DB_PASSWORD: ${self:custom.secrets.${self:provider.stage}.db_password}
    #DB_HOST: ${self:custom.secrets.${self:provider.stage}.db_host}
    DB_PORT: ${self:custom.secrets.${self:provider.stage}.db_port}
    #ACCOUNT_ID: ${self:custom.secrets.${self:provider.stage}.account_id}
    #REGION: ${self:custom.secrets.${self:provider.stage}.region}
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
